//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDEServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROMANNB\\SQLEXPRESS;Initial Catalog=C:\\USERS\\ROMAN\\DOCUMENTS\\DDEEXPORT" +
            "SAMPLE\\DDEEXPORTSAMPLE\\ПРОГРАММА\\DDESAMPLE\\BIN\\DEBUG\\DATABASE1.MDF;Integrated Se" +
            "curity=True;Encrypt=False;TrustServerCertificate=True")]
        public string C__USERS_ROMAN_DOCUMENTS_DDEEXPORTSAMPLE_DDEEXPORTSAMPLE_ПРОГРАММА_DDESAMPLE_BIN_DEBUG_DATABASE1_MDFConnectionString {
            get {
                return ((string)(this["C__USERS_ROMAN_DOCUMENTS_DDEEXPORTSAMPLE_DDEEXPORTSAMPLE_ПРОГРАММА_DDESAMPLE_BIN_" +
                    "DEBUG_DATABASE1_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROMANNB\\SQLEXPRESS;Initial Catalog=C:\\CANDLEBASE\\DATABASE1.MDF;Integr" +
            "ated Security=True;Encrypt=False;TrustServerCertificate=True")]
        public string C__CANDLEBASE_DATABASE1_MDFConnectionString {
            get {
                return ((string)(this["C__CANDLEBASE_DATABASE1_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROMANNB-ПК;Initial Catalog=C:\\CANDLEBASE\\DATABASE1.MDF;Integrated Sec" +
            "urity=True")]
        public string C__CANDLEBASE_DATABASE1_MDFConnectionString1 {
            get {
                return ((string)(this["C__CANDLEBASE_DATABASE1_MDFConnectionString1"]));
            }
        }
    }
}
